name: Build and Release

on:
  push:
    branches: ["main"]

# Declare default permissions as read only.
permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - uses: actions/setup-java@v3
        with:
          java-version: "11.x"
          distribution: temurin

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        id: tagger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - run: echo $KEY_JKS | base64 --decode > ../keys/key.jks && flutter build apk && flutter build appbundle
        working-directory: ./app
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          VERSION: ${{ steps.tagger.outputs.new_tag }}

      - run: fastlane android deploy
        working-directory: ./app
        env:
          GOOGLE_JSON_KEY: ${{ secrets.GOOGLE_JSON_KEY }}
          VERSION: ${{ steps.tagger.outputs.new_tag }}

      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/app/outputs/flutter-apk/app-release.apk
            app/build/app/outputs/bundle/release/app-release.aab
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true
